## Direct connection configuration
## For IPV6 network

#dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
#dataSource.user=postgres
#dataSource.password=Pyrzqxgl$25
#dataSource.databaseName=postgres
#dataSource.portNumber=5432
#dataSource.serverName=db.pdzvbcrfvtmagnxwxkup.supabase.co
#maximumPoolSize=2


## Session pooler configuration
## Only when connecting through an IPV4 network

dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
dataSource.user=postgres.pdzvbcrfvtmagnxwxkup
dataSource.password=Pyrzqxgl$25
dataSource.databaseName=postgres
dataSource.portNumber=5432
dataSource.serverName=aws-0-us-west-1.pooler.supabase.com
maximumPoolSize=2